routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\BarangMasukController;
use App\Http\Controllers\TransaksiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('barang',BarangController::class);
Route::resource('barang_masuk',BarangMasukController::class);
Route::resource('transaksi',TransaksiController::class);

app/Models/Transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    use HasFactory;
    
    protected $fillable = ['title', 'author_id', 'amount', 'cover'];
    public $timestamps = true;
    public function barang()
    {
        // data dari Model "Book" bisa di miliki oleh model "Author"
        // melalui fk "author_id"
        return $this->belongsTo('App\Models\Barang', 'barang_id');
    }   
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaksi;
use App\Models\Barang;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use session;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transaksi = Transaksi::All();
        return view('transaksi.index',compact('transaksi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $barang = barang::all();
        return view('transaksi.create',compact('barang'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        

        // $barang = Barang::findOrFail($request->barang_id);
        // $barang->jumlah     -= $request->qty;
        // $barang->harga       = $request->harga;
        // $barang->total_harga = $request->total_harga;
        // $barang->save();

        // Session::flash('flash_message','transaksi added');

    

        $transaksi = new Transaksi;
        $transaksi->barang_id   = $request->barang_id;
        $transaksi->harga       = $request->harga;
        $transaksi->qty         = $request->qty;
        $transaksi->total_harga = $transaksi->harga * $transaksi->qty;
        $transaksi->save();

        // Pengurangan STOK Barang
         $barang = Barang::findOrFail($request->barang_id);
         $barang->jumlah -= $request->qty;
         $barang->save();
        
        return redirect()->route('transaksi.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function show(Transaksi $transaksi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaksi $transaksi)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaksi $transaksi)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaksi = Transaksi::findOrFail($id);
        $transaksi->delete();

         $barang = Barang::findOrFail($barang->id);
         $barang->jumlah += $transaksi;
         $barang->save();
        return redirect()->route('transaksi.index');
    
    }

    // menentuka jumlah keseluruhan laporan TRANSAKSI
    public function laporan(){
        $transaksi = DB::table('users')
                        ->select('count(id) as laporan')
                        ->groupBy('id')
                        ->get();
        return view('home',compact('transaksi'));
    }
}

resources/views/transaksi/create.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Startmin - Bootstrap Admin Theme</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('/backend/css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{{ asset('/backend/css/metisMenu.min.css')}}" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="{{ asset('/backend/css/timeline.css')}}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('/backend/css/startmin.css')}}" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="{{ asset('/backend/css/morris.css')}}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{{ asset('/backend/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

                {{-- BAGIAN NAVBAR --}}
                @include('layouts.bagian.navbar')
                {{-- /BAGIAN NAVBAR --}}

                {{-- BAGIAN SIDEBAR --}}
                @include('layouts.bagian.sidebar')
                {{-- /BAGIAN SIDEBAR --}}
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Tambah Transaksi</h1>
                        </div>

                        {{-- BAGIAN CONTENT --}}
                            <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Basic Form Elements
                                </div>
                                    <form Action="{{route('transaksi.store')}}" method="post">
                                     @csrf
                                        <div class="panel-body">
                                            <label>Nama Barang</label>
                                            <select name="barang_id" class="form-control">
                                                   @foreach($barang as $data)
                                                       <option value="{{$data->id}}">{{$data->nama}}</option>
                                                  @endforeach
                                            </select>
                                        </div>
                                        <div class="panel-body">
                                            <label>Harga</label></label>
                                            <input type="number" class="form-control" name="harga">
                                        </div>
                                        <div class="panel-body">
                                            <label>Qty</label></label>
                                            <input type="number" class="form-control" name="qty">
                                        </div>
                                        {{-- <div class="panel-body">
                                            <label>Total Harga</label></label>
                                            <input type="number" class="form-control" name="total_harga">
                                        </div> --}}
                                        <div class="panel-body">
                                           <button type="reset" class="btn btn-warning">Reset</button>
                                           <button type="submit" class="btn btn-primary">Tambah</button>
                                        </div>
                                    </form>
                            </div>
                            <!-- /.panel -->
                        </div>
                        <!-- /.col-lg-12 -->
                    </div> 
                        {{-- BAGIAN CONTENT --}}


                    </div>
                </div>
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="{{ asset('/backend/js/jquery.min.js')}}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('/backend/js/bootstrap.min.js')}}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{{ asset('/backend/js/metisMenu.min.js')}}"></script>

        <!-- Morris Charts JavaScript -->
        <script src="{{ asset('/backend/js/raphael.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris-data.js')}}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="../js/startmin.js')}}"></script>

    </body>
</html>

resources/views/transaksi/index.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Startmin - Bootstrap Admin Theme</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('/backend/css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{{ asset('/backend/css/metisMenu.min.css')}}" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="{{ asset('/backend/css/timeline.css')}}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('/backend/css/startmin.css')}}" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="{{ asset('/backend/css/morris.css')}}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{{ asset('/backend/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

                {{-- BAGIAN NAVBAR --}}
                @include('layouts.bagian.navbar')
                {{-- /BAGIAN NAVBAR --}}

                {{-- BAGIAN SIDEBAR --}}
                @include('layouts.bagian.sidebar')
                {{-- /BAGIAN SIDEBAR --}}
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Transaksi</h1>
                        </div>

                        {{-- BAGIAN CONTENT --}}
                              <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Data Transaksi
                                    <a href="{{route('transaksi.create')}}" class="btn btn-primary">Tambah Data</a>
                                </div>
                                
                                <!-- /.panel-heading -->
                                <div class="panel-body">
                                    <div class="table-responsive table-bordered">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>No</th>
                                                    <th>Nama Barang</th>
                                                    <th>Harga</th>
                                                    <th>Qty</th>
                                                    <th>Total Harga</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                             @php $no=1; @endphp
                                                  @foreach($transaksi as $data)
                                                <tr>
                                                    <td>{{$no++}}</td>
                                                    <td>{{$data->barang->nama}}</td>
                                                    <td>{{$data->harga}}</td>
                                                    <td>{{$data->qty}}</td>
                                                    <td>{{$data->total_harga}}</td>
                                                    <td>
                                                     <form action="{{route('transaksi.destroy',$data->id)}}" method="post">
                                                        @method('delete')
                                                        @csrf
                                                            <a href="{{route('transaksi.edit',$data->id)}}" class="btn btn-success">Ubah</a>
                                                            <a href="{{route('transaksi.show',$data->id)}}" class="btn btn-warning">Detail</a>
                                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Apakah anda yakin menghapus ini?');">Delete</button>
                                                    </form>
                                                    </td>
                                                </tr>
                                               @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.table-responsive -->
                                </div>
                                <!-- /.panel-body -->
                            </div>
                            <!-- /.panel -->
                        </div>
                        {{-- BAGIAN CONTENT --}}
                    </div>
                </div>
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="{{ asset('/backend/js/jquery.min.js')}}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('/backend/js/bootstrap.min.js')}}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{{ asset('/backend/js/metisMenu.min.js')}}"></script>

        <!-- Morris Charts JavaScript -->
        <script src="{{ asset('/backend/js/raphael.min.js')}}"></script>
        <script src="{{ asset('/23LW, MMML /js/morris.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris-data.js')}}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="../js/startmin.js')}}"></script>

    </body>
</html>