routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\BarangMasukController;
use App\Http\Controllers\TransaksiController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('barang',BarangController::class);
Route::resource('barang_masuk',BarangMasukController::class);
Route::resource('transaksi',TransaksiController::class);

app/Models/Barang.php
<?php

namespace App\Models;
use Alert;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    use HasFactory;
    protected $fillable = ['nama','jumlah'];
    public $timestamps = true;

    public function barang_masuk()
    {
        // data model "Author" bisa memiliki banyak data
        // dari model "Book" melalui fk "author_id"
        $this->hasMany('App\Models\barang_masuk', 'id_barang');
    }
    // UPLOAD IMAGE
    public function image()
    {
        if ($this->cover && file_exists(public_path('image/book/' . $this->cover))) {
            return asset('image/book/' . $this->cover);
        } else {
            return asset('image/no_image.png');
        }
    }

    public function deleteImage()
    {
        if ($this->cover && file_exists(public_path('image/book/' . $this->cover))) {
            return unlink(public_path('image/book/' . $this->cover));
        }

    }
    // public static function boot()
    // {
    //     parent::boot();
    //     self::deleting(function ($barang) {
    //         if ($barang->barang_masuk->count() > 0) {
    //             Alert::error('Failed', 'Data not deleted');
    //             return false;
    //         }
    //     });
    // }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\Barang;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $barang = Barang::All();
        return view('barang.index', compact('barang'));
       
        //Ubah ke Json
        // return response()->json([
        //     'success' => true,
        //     'message' => 'List Data Barang',
        //     'data'    => $barang  
        // ], 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('barang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validasi data
        $validated = $request->validate([
            'supplier' => 'required',
            'nama' => 'required',
            'cover' => 'required|image|max:2048',
            'stok' => 'required|numeric'
        ]);

        $barang = new Barang;
        $barang->supplier = $request->supplier;
        $barang->nama = $request->nama;
        // upload image / foto
        if ($request->hasFile('cover')) {
            $image = $request->file('cover');
            $name = rand(1000, 9999) . $image->getClientOriginalName();
            $image->move('image/book/', $name);
            $barang->cover = $name;
        }
        $barang->stok = $request->stok;
        $barang->save();
        
        return redirect()->route('barang.index');

        
        // return response()->json([
        //     'success' => true,
        //     'message' => 'List Data Barang',
        //     'data'    => $barang  
        // ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $barang = Barang::findOrFail($id);
         return view('barang.show', compact('barang'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $barang = Barang::findOrFail($id);
         return view('barang.edit', compact('barang'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         // validasi data
         $validated = $request->validate([
            'supplier' => 'required',
            'nama' => 'required',
            'stok' => 'required',
        ]);

        $brang = Barang::findOrFail($id);
        $barang->supplier = $request->supplier;
        $barang->nama = $request->nama;
        $barang->stok = $request->stok;
        $barang->save();
        return redirect()->route('barang.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $barang = Barang::findOrFail($id);
        $barang->delete();
        return redirect()->route('barang.index');
    }
}

resources/views/barang/create.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Startmin - Bootstrap Admin Theme</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('/backend/css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{{ asset('/backend/css/metisMenu.min.css')}}" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="{{ asset('/backend/css/timeline.css')}}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('/backend/css/startmin.css')}}" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="{{ asset('/backend/css/morris.css')}}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{{ asset('/backend/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

                {{-- BAGIAN NAVBAR --}}
                @include('layouts.bagian.navbar')
                {{-- /BAGIAN NAVBAR --}}

                {{-- BAGIAN SIDEBAR --}}
                @include('layouts.bagian.sidebar')
                {{-- /BAGIAN SIDEBAR --}}
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Tambah Barang</h1>
                        </div>

                        {{-- BAGIAN CONTENT --}}
                            <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Basic Form Elements
                                </div>
                                    <form Action="{{route('barang.store')}}" method="post" enctype="multipart/form-data">
                                     @csrf
                                        <div class="panel-body">
                                            <label>Nama Supplier</label>
                                            <input type="text" class="form-control" name="supplier" required>
                                        </div>
                                        <div class="panel-body">
                                            <label>Nama Barang</label>
                                            <input type="text" class="form-control" name="nama" required>
                                        </div>
                                        <div class="panel-body">
                                            <label>Gambar</label>
                                            <input type="file" class="form-control" name="cover" required>
                                        </div>
                                        <div class="panel-body">
                                            <label>Stok</label>
                                            <input type="text" class="form-control" name="stok" required>
                                            @if($errors->has('stok'))
                                                <span class="invalid-feedback text-danger">{{ $errors->first('stok') }}</span>
                                            @endif
                                        </div>
                                        <div class="panel-body">
                                           <button type="reset" class="btn btn-warning">Reset</button>
                                           <button type="submit" class="btn btn-primary">Tambah</button>
                                        </div>
                                    </form>
                            </div>
                            <!-- /.panel -->
                        </div>
                        <!-- /.col-lg-12 -->
                    </div> 
                        {{-- BAGIAN CONTENT --}}


                    </div>
                </div>
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="{{ asset('/backend/js/jquery.min.js')}}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('/backend/js/bootstrap.min.js')}}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{{ asset('/backend/js/metisMenu.min.js')}}"></script>

        <!-- Morris Charts JavaScript -->
        <script src="{{ asset('/backend/js/raphael.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris-data.js')}}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="../js/startmin.js')}}"></script>

    </body>
</html>

resources/views/barang/edit.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Startmin - Bootstrap Admin Theme</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('/backend/css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{{ asset('/backend/css/metisMenu.min.css')}}" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="{{ asset('/backend/css/timeline.css')}}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('/backend/css/startmin.css')}}" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="{{ asset('/backend/css/morris.css')}}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{{ asset('/backend/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

                {{-- BAGIAN NAVBAR --}}
                @include('layouts.bagian.navbar')
                {{-- /BAGIAN NAVBAR --}}

                {{-- BAGIAN SIDEBAR --}}
                @include('layouts.bagian.sidebar')
                {{-- /BAGIAN SIDEBAR --}}
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Ubah Barang</h1>
                        </div>

                        {{-- BAGIAN CONTENT --}}
                            <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Ubah Data Barang
                                </div>
                                    <form Action="{{route('barang.update',$barang->id)}}" method="post">
                                      @csrf
                                      @method('put')
                                        <div class="panel-body">
                                            <label>Nama</label>
                                            <input type="text" class="form-control" name="nama" value="{{$barang->nama}}">
                                        </div>
                                        <div class="panel-body">
                                            <label>Jumlah</label>
                                            <input type="number" class="form-control" name="jumlah" value="{{$barang->jumlah}}">
                                        </div>
                                        <div class="panel-body">
                                           <button type="reset" class="btn btn-warning">Reset</button>
                                           <button type="submit" class="btn btn-primary">Ubah</button>
                                        </div>
                                    </form>
                            </div>
                            <!-- /.panel -->
                        </div>
                        <!-- /.col-lg-12 -->
                    </div> 
                        {{-- BAGIAN CONTENT --}}


                    </div>
                </div>
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="{{ asset('/backend/js/jquery.min.js')}}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('/backend/js/bootstrap.min.js')}}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{{ asset('/backend/js/metisMenu.min.js')}}"></script>

        <!-- Morris Charts JavaScript -->
        <script src="{{ asset('/backend/js/raphael.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris-data.js')}}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="../js/startmin.js')}}"></script>

    </body>
</html>

resources/views/barang/index.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Startmin - Bootstrap Admin Theme</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('/backend/css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{{ asset('/backend/css/metisMenu.min.css')}}" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="{{ asset('/backend/css/timeline.css')}}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('/backend/css/startmin.css')}}" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="{{ asset('/backend/css/morris.css')}}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{{ asset('/backend/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

                {{-- BAGIAN NAVBAR --}}
                @include('layouts.bagian.navbar')
                {{-- /BAGIAN NAVBAR --}}

                {{-- BAGIAN SIDEBAR --}}
                @include('layouts.bagian.sidebar')
                {{-- /BAGIAN SIDEBAR --}}
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Barang</h1>
                        </div>
                        {{-- BAGIAN CONTENT --}}
                              <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Data Barang
                                    <a href="{{route('barang.create')}}" class="btn btn-primary">Tambah Data</a>
                                </div>
                                
                                <!-- /.panel-heading -->
                                <div class="panel-body">
                                    <div class="table-responsive table-bordered">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>No</th>
                                                    <th>Supplier</th>
                                                    <th>Barang</th>
                                                    <th>Gambar</th>
                                                    <th>Stok</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                             @php $no=1; @endphp
                                                  @foreach($barang as $data)
                                                <tr>
                                                    <td>{{$no++}}</td>
                                                    <td>{{$data->supplier}}</td>
                                                    <td>{{$data->nama}}</td>
                                                    <td><img src="{{$data->image()}}" alt="" style="width:150px; height:150px;" alt="Cover"></td>
                                                    <td>{{$data->stok}}</td>
                                                    <td>
                                                     <form action="{{route('barang.destroy',$data->id)}}" method="post">
                                                        @method('delete')
                                                        @csrf
                                                            <a href="{{route('barang.edit',$data->id)}}" class="btn btn-success">Ubah</a>
                                                            <a href="{{route('barang.show',$data->id)}}" class="btn btn-warning">Detail</a>
                                                            <button type="submit" class="btn btn-danger delete-confirm">Delete</button>
                                                    </form>
                                                    </td>
                                                </tr>
                                               @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.table-responsive -->
                                </div>
                                <!-- /.panel-body -->
                            </div>
                            <!-- /.panel -->
                        </div>
                        {{-- BAGIAN CONTENT --}}
                    </div>
                </div>
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="{{ asset('/backend/js/jquery.min.js')}}"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script>
            
            $(".delete-confirm").click(function (event) {
                var form = $(this).closest("form");
                var name = $(this).data("name");
                event.preventDefault();
                Swal.fire({
                    title: "Are you sure?",
                    text: "You won't be able to revert this!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#3085d6",
                    cancelButtonColor: "#d33",
                    confirmButtonText: "Yes, delete it!",
                }).then((result) => {
                    if (result.isConfirmed) {
                        form.submit();
                    }
                });
            });
        </script>
        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('/backend/js/bootstrap.min.js')}}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{{ asset('/backend/js/metisMenu.min.js')}}"></script>

        <!-- Morris Charts JavaScript -->
        <script src="{{ asset('/backend/js/raphael.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris-data.js')}}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="../js/startmin.js')}}"></script>

    </body>
</html>

resources/views/barang/show.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Startmin - Bootstrap Admin Theme</title>

        <!-- Bootstrap Core CSS -->
        <link href="{{ asset('/backend/css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{{ asset('/backend/css/metisMenu.min.css')}}" rel="stylesheet">

        <!-- Timeline CSS -->
        <link href="{{ asset('/backend/css/timeline.css')}}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{{ asset('/backend/css/startmin.css')}}" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="{{ asset('/backend/css/morris.css')}}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{{ asset('/backend/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

                {{-- BAGIAN NAVBAR --}}
                @include('layouts.bagian.navbar')
                {{-- /BAGIAN NAVBAR --}}

                {{-- BAGIAN SIDEBAR --}}
                @include('layouts.bagian.sidebar')
                {{-- /BAGIAN SIDEBAR --}}
            </nav>

            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Tambah Barang</h1>
                        </div>

                        {{-- BAGIAN CONTENT --}}
                          <div class="row">
                               <div class="col-lg-4">
                                   <div class="panel panel-primary">
                                        <div class="panel-heading">
                                                  Detail Barang
                                                  </div>
                                                  <div class="panel-body">
                                                  <h2>{{$barang->nama}}</h2>
                                                  <p><i><b>Stok = {{$barang->jumlah}}</b></i></p>
                                                  </div>
                                                  <div class="panel-footer">
                                                  </div>
                                    </div>
                               </div>
                              <!-- /.col-lg-12 -->
                          </div> 
                        {{-- BAGIAN CONTENT --}}


                    </div>
                </div>
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="{{ asset('/backend/js/jquery.min.js')}}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('/backend/js/bootstrap.min.js')}}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{{ asset('/backend/js/metisMenu.min.js')}}"></script>

        <!-- Morris Charts JavaScript -->
        <script src="{{ asset('/backend/js/raphael.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris.min.js')}}"></script>
        <script src="{{ asset('/backend/js/morris-data.js')}}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="../js/startmin.js')}}"></script>

    </body>
</html>